[package]
name = "arena"
version = "0.1.0"
edition = "2021"
description = "A thread-safe arena bytes allocator"
authors = ["MrGunflame <git@robbsrv.de>"]
repository = "https://github.com/MrGunflame/arena-rs"
documentation = "https://docs.rs/arena"
license = "MIT OR Apache-2.0"

[dependencies]
